### ISSUE TITLE
Site will not work on Azure Webapps

### ISSUE THREAD

**Issue by molant** [greenyouse/yum-foodz#1]
We cannot run any compile process, site is deployed as is. I recommend adding the compile output to this repo so it can be deployed.

Also do not hardcode the port. You should do something like:

``` javascript
var port = process.env.PORT || 5000;
```

/cc @aarongustafson

**Comment by greenyouse** [comment]
OK, thanks for the feedback. I added compiled files to `/dist` and followed your suggestion for switching the port. Are there any other things to fix for Azure?

**Comment by molant** [comment]
Working! http://yum-foodz-10kapart2016.azurewebsites.net/recipes

**Comment by greenyouse** [comment]
Hi, I just checked the site and it looks like the `manifest.json` file might be missing. In recent versions of Chrome, Firefox, and Opera it will keep the ServiceWorker from starting up. Could this file be added to the deploy too?

**Comment by greenyouse** [comment]
I tried re-deploying the project with the link provided by the contest. I'm thinking to leave this issue open until the `manifest.json` is included. Were there any issues uploading that file during the last deploy?

Thanks in advance for any help!

**Comment by greenyouse** [comment]
@molant any update? Sorry for any notification spam

**Comment by molant** [comment]
The file is there, the problem is that it seems you don't have an `app.get('/manifest.json')` to deliver that file via node and IIS will not do that for you unless you configure the web.config correctly.
![image](https://cloud.githubusercontent.com/assets/606594/19278446/138ba688-8f92-11e6-906d-d1a0299542ea.png)

**Comment by greenyouse** [comment]
I thought by using the StaticContent rule in web.config I could serve the static files though

``` xml
      <!-- First we consider whether the incoming URL matches a physical file in the /public folder -->
      <!-- using dist instead -->
      <rule name="StaticContent">
        <action type="Rewrite" url="dist{REQUEST_URI}"/>
      </rule>
```

The ServiceWorker tries to fetch `/manifest.json` when the app starts up but there must still be a problem with my web.config. I can add a node endpoint for it but is there any way to have the StaticContent rule handle this instead?

**Comment by greenyouse** [comment]
@molant I added `app.get('/manifest.json')` but it still won't work for the ServiceWorker because it needs to fetch the file without node. Are there any tweaks to the web.config that could allow for serving this as part of StaticContent?

**Comment by molant** [comment]
I don't understand why node will be a problem for the service worker. What would be the difference between serving this file from IIS, Apache or Node? All act as web servers and should be transparent for the service worker.
Also I think that the time to update files is closed.
Pinging @aarongustafson

**Comment by greenyouse** [comment]
OK, I can close the issue if there's no obvious way to get it working. I was hoping the problem was with IIS and there would be an easy fix. Thanks again for the help and sorry this dragged on for a little while.

**Comment by aarongustafson** [comment]
I suspect the issue might be IIS not knowing the MIME type for the JSON file. Does that seem like a reasonable assumption @molant? I know we ran into that with WebP too. Adding the MIME in the `web.config` may solve the issue for the ServiceWorker.

```
<staticContent>
  <mimeMap fileExtension=".json" mimeType="application/json" />
</staticContent>
```

**Comment by molant** [comment]
and how did I miss that? It is fixed now.

**Comment by greenyouse** [comment]
Awesome! Thanks for getting it running!
